name: cleantechbrokers
favicon: null
layout_spectrum: 0.6027397671714425
typography_spectrum: 0.5072726986836642
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12102127098478377
  lightness: 0.08429208165034652
  saturation: 0.7739094796124846
  rhythmicContrast: 0.3547894274815917
purpose: []
